# Generated by Django 5.2.1 on 2025-06-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0017_alter_genperson_creation_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
