# Generated by Django 5.2.1 on 2025-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModule', '0019_genmember_section_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmember',
            name='couch_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
